language: scala

jdk:
  - oraclejdk8

sudo: false

addons:
    apt:
        packages:
            - gcc-multilib
            - g++-multilib
            - libstdc++6:i386
            - libgcc1:i386
            - zlib1g:i386
            - libncurses5:i386

scala:
    - 2.11.8

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "*.lock" | xargs rm

cache:
    directories:
        - $HOME/.ivy2
        - $HOME/.sbt

android:
    components:
        - tools
        - build-tools-25.0.2
        - extra-android-m2repository
        - extra-google-m2repository

install:
    - ./travis-ci/setup.sh
    - export NDK_CCACHE=ccache
    - export ARCH=`uname -m`
    - export ANDROID_NDK_HOME=$HOME/.android/android-ndk-r12b
    - export ANDROID_HOME=$HOME/.android/android-sdk-linux
    - export PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
    - cp local.properties.travis local.properties

script:
    - sbt native-build android:package-release

deploy:
#  - provider: testfairy
#    api-key: "0b74de16d287f975b6abdfe59d5688f47423aada"
#    skip_cleanup: true
#    app-file: ./target/android/output/shadowsocksr-release.apk
#    keystore-file: travis.keystore
#    storepass: travis
#    alias: travis
#    on:
#       all_branches: true
  - provider: releases # 部署到GitHub Release，除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
    api_key:           # 填写GitHub的token （Settings -> Personal access tokens -> Generate new token）
      secure: $GH_TOKEN
    file: ./target/android/output/shadowsocksr-release.apk
    skip_cleanup: true     # 设置为true以跳过清理,不然apk文件就会被清理
    on:     # 发布时机           
      branch: t-scala   
